Update build_loop.yml

diff --git a/.github/workflows/build_loop.yml b/.github/workflows/build_loop.yml
--- a/.github/workflows/build_loop.yml
+++ b/.github/workflows/build_loop.yml
@@ -1,5 +1,6 @@
 name: 4. Build Loop
 run-name: Build Loop (${{ github.ref_name }})
+
 on:
   workflow_dispatch:
   schedule:
@@ -10,11 +11,10 @@ on:
 env:
   GH_PAT: ${{ secrets.GH_PAT }}
   UPSTREAM_REPO: LoopKit/LoopWorkspace
-  UPSTREAM_BRANCH: ${{ github.ref_name }} # branch on upstream repository to sync from (replace with specific branch name if needed)
-  TARGET_BRANCH: ${{ github.ref_name }} # target branch on fork to be kept in sync
+  UPSTREAM_BRANCH: ${{ github.ref_name }} # branch on upstream repository to sync from
+  TARGET_BRANCH: ${{ github.ref_name }}   # target branch on fork
 
 jobs:
-  # use a single runner for these sequential steps
   check_status:
     runs-on: ubuntu-latest
     name: Check status to decide whether to build
@@ -24,21 +24,16 @@ jobs:
       NEW_COMMITS: ${{ steps.sync.outputs.has_new_commits }}
       IS_SECOND_IN_MONTH: ${{ steps.date-check.outputs.is_second_instance }}
 
-    # Check GH_PAT, sync repository, check day in month
     steps:
       - name: Access
         id: workflow-permission
         run: |
           # Validate Access Token
-
-          # Ensure that gh exit codes are handled when output is piped.
           set -o pipefail
 
-          # Define patterns to validate the access token (GH_PAT) and distinguish between classic and fine-grained tokens.
           GH_PAT_CLASSIC_PATTERN='^ghp_[a-zA-Z0-9]{36}$'
           GH_PAT_FINE_GRAINED_PATTERN='^github_pat_[a-zA-Z0-9]{22}_[a-zA-Z0-9]{59}$'
 
-          # Validate Access Token (GH_PAT)
           if [ -z "$GH_PAT" ]; then
             failed=true
             echo "::error::The GH_PAT secret is unset or empty. Set it and try again."
@@ -53,7 +48,6 @@ jobs:
               echo "The GH_PAT secret does not have a known token format."
             fi
 
-            # Attempt to capture the x-oauth-scopes scopes of the token.
             if ! scopes=$(curl -sS -f -I -H "Authorization: token $GH_PAT" https://api.github.com | { grep -i '^x-oauth-scopes:' || true; } | cut -d ' ' -f2- | tr -d '\r'); then
               failed=true
               if [ $unknown_format ]; then
@@ -73,14 +67,13 @@ jobs:
               else
                 echo "The GH_PAT secret is valid and can be used to connect to GitHub, but it only provides the following permission scopes: $scopes"
               fi
-              echo "::error::The GH_PAT secret is lacking at least the 'repo' permission scope required to access the Match-Secrets repository. Update the token permissions at https://github.com/settings/tokens (to include the 'repo' and 'workflow' scopes) and try again."
+              echo "::error::The GH_PAT secret is lacking at least the 'repo' permission scope required. Update the token permissions (include 'repo' and 'workflow') and try again."
             else
-              echo "The GH_PAT secret is valid and can be used to connect to GitHub, but it does not provide inspectable scopes. Assuming that the 'repo' and 'workflow' permission scopes required to access the Match-Secrets repository and perform automations are present."
+              echo "The GH_PAT secret is valid but does not provide inspectable scopes. Assuming required permissions are present."
               echo "has_permission=true" >> $GITHUB_OUTPUT
             fi
           fi
 
-          # Exit unsuccessfully if secret validation failed.
           if [ $failed ]; then
             exit 2
           fi
@@ -93,9 +86,8 @@ jobs:
         with:
           token: ${{ secrets.GH_PAT }}
 
-      # This syncs any target branch to upstream branch of the same name
       - name: Sync upstream changes
-        if: | # do not run the upstream sync action on the upstream repository
+        if: |
           steps.workflow-permission.outputs.has_permission == 'true' &&
           vars.SCHEDULED_SYNC != 'false' && github.repository_owner != 'LoopKit'
         id: sync
@@ -107,7 +99,6 @@ jobs:
           upstream_sync_branch: ${{ env.UPSTREAM_BRANCH }}
           upstream_sync_repo: ${{ env.UPSTREAM_REPO }}
 
-      # Display a sample message based on the sync output var 'has_new_commits'
       - name: New commits found
         if: |
           steps.workflow-permission.outputs.has_permission == 'true' &&
@@ -132,14 +123,11 @@ jobs:
           echo "### :calendar: Scheduled Sync and Build Disabled :mobile_phone_off:" >> $GITHUB_STEP_SUMMARY
           echo "You have not yet configured the scheduled sync and build for Loop's browser build." >> $GITHUB_STEP_SUMMARY
           echo "Synchronizing your fork of <code>LoopWorkspace</code> with the upstream repository <code>LoopKit/LoopWorkspace</code> will be skipped." >> $GITHUB_STEP_SUMMARY
-          echo "If you want to enable automatic builds and updates for your Loop, please follow the instructions \
-                under the following path <code>LoopWorkspace/fastlane/testflight.md</code>." >> $GITHUB_STEP_SUMMARY
+          echo "If you want to enable automatic builds and updates for your Loop, please follow the instructions under <code>LoopWorkspace/fastlane/testflight.md</code>." >> $GITHUB_STEP_SUMMARY
 
-      # Set a logic flag if this is the second instance of this day-of-week in this month
       - name: Check if this is the second time this day-of-week happens this month
         id: date-check
         run: |
-          DAY_OF_MONTH=$(date +%-d)
           WEEK_OF_MONTH=$(( ($(date +%-d) - 1) / 7 + 1 ))
           if [[ $WEEK_OF_MONTH -eq 2 ]]; then
             echo "is_second_instance=true" >> "$GITHUB_OUTPUT"
@@ -147,9 +135,6 @@ jobs:
             echo "is_second_instance=false" >> "$GITHUB_OUTPUT"
           fi
 
-  # Checks if Distribution certificate is present and valid, optionally nukes and
-  # creates new certs if the repository variable ENABLE_NUKE_CERTS == 'true'
-  # only run if a build is planned
   check_certs:
     needs: [check_status]
     name: Check certificates
@@ -160,7 +145,6 @@ jobs:
         (vars.SCHEDULED_BUILD != 'false' && needs.check_status.outputs.IS_SECOND_IN_MONTH == 'true') ||
         (vars.SCHEDULED_SYNC != 'false' && needs.check_status.outputs.NEW_COMMITS == 'true' )
 
-  # Builds Loop
   build:
     name: Build
     needs: [check_certs, check_status]
@@ -182,34 +166,18 @@ jobs:
           submodules: recursive
           ref: ${{ env.TARGET_BRANCH }}
 
-      # Customize Loop: Download and apply patches
-      - name: Customize Loop
+      - name: Customize Loop (patches folder)
         run: |
-          # LoopWorkspace patches
-          # -applies any patches located in the LoopWorkspace/patches/ directory
           if $(ls ./patches/* &> /dev/null); then
             git apply ./patches/* --allow-empty -v --whitespace=fix
           fi
 
-          # Submodule Loop patches:
-          # Template for customizing submodule Loop (changes Loop app name to "CustomLoop")
-          # Remove the "#" sign from the beginning of the line below to activate:
-          #curl https://github.com/loopnlearn/Loop/commit/d206432b024279ef710df462b20bd464cd9682d4.patch | git apply --directory=Loop -v --whitespace=fix
-
-          # Submodule LoopKit patches:
-          # General template for customizing submodule LoopKit
-          # Copy url from a GitHub commit or pull request and insert below, and remove the "#" sign from the beginning of the line to activate:
-          #curl url_to_github_commit.patch | git apply --directory=LoopKit -v --whitespace=fix
-
-      # ✅ Apply Loop and Learn prepared customizations (Profiles Save/Load)
-      # NOTE: This uses Loop and Learn's CustomizationSelect script (not LoopKit's).
-      - name: Apply L&L Customizations (Profiles)
-        env:
-          CUSTOMIZATION_SELECT: profiles
+      # ✅ Correct way to add Profiles Save/Load using Loop & Learn script
+      - name: Apply CustomizationSelect (Profiles Save/Load)
         run: |
-          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/loopandlearn/lnl-scripts/dev/CustomizationSelect.sh)"
+          set -euo pipefail
+          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/loopandlearn/lnl-scripts/main/CustomizationSelect.sh)" profiles
 
-      # Patch Fastlane Match to not print tables
       - name: Patch Match Tables
         run: |
           TABLE_PRINTER_PATH=$(ruby -e 'puts Gem::Specification.find_by_name("fastlane").gem_dir')/match/lib/match/table_printer.rb
@@ -220,15 +188,12 @@ jobs:
             exit 1
           fi
 
-      # Install project dependencies
       - name: Install Project Dependencies
         run: bundle install
 
-      # Sync the GitHub runner clock with the Windows time server (workaround as suggested in https://github.com/actions/runner/issues/2996)
       - name: Sync clock
         run: sudo sntp -sS time.windows.com
 
-      # Build signed Loop IPA file
       - name: Fastlane Build & Archive
         run: bundle exec fastlane build_loop
         env:
@@ -239,7 +204,6 @@ jobs:
           FASTLANE_KEY: ${{ secrets.FASTLANE_KEY }}
           MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
 
-      # Upload to TestFlight
       - name: Fastlane upload to TestFlight
         run: bundle exec fastlane release
         env:
@@ -250,7 +214,6 @@ jobs:
           FASTLANE_KEY: ${{ secrets.FASTLANE_KEY }}
           MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
 
-      # Upload Build artifacts
       - name: Upload build log, IPA and Symbol artifacts
         if: always()
         uses: actions/upload-artifact@v4
